# Generated by Django 5.0.6 on 2024-06-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framework',
            old_name='Language',
            new_name='language',
        ),
    ]
